# image_root: '/export/share/datasets/vision/coco/images/'
image_root: 'D:\\neural_network/coco/images/'
ann_root: 'D:\\neural_network/annotation/karpathy'
coco_gt_root: 'D:\\neural_network/annotation/coco_gt'
ann_root_DCC: 'D:\\neural_network/annotation/DCC'
ann_root_mine: 'D:\\neural_network/annotation/jxh'


paper_own: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'



# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 1      # [author] 32
init_lr: 5e-6      # [author] 1e-5


# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 1e-7
max_epoch: 5     # [author] 5

# finetune setting
finetune_lr: 5e-6
finetune_epoch: 1

# eval时所用batch size
eval_batch_size: 64